-- Initial Schema for ClinicPage SaaS

-- 1. Users / Profiles
CREATE TABLE users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    name TEXT,
    plan TEXT DEFAULT 'free', -- 'free', 'pro', 'clinic'
    is_admin BOOLEAN DEFAULT FALSE,
    ai_credits_used INTEGER DEFAULT 0,
    ai_credits_limit INTEGER DEFAULT 3,
    stripe_customer_id TEXT,
    stripe_subscription_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Landing Pages
CREATE TABLE landing_pages (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'draft', -- 'draft', 'published', 'archived'
    template_id TEXT,
    briefing JSONB,
    sections JSONB, -- Stores all section content generated by AI
    theme JSONB, -- Colors, typography, etc.
    seo JSONB, -- Meta tags, OG tags
    integrations JSONB, -- WhatsApp, GTM, etc.
    custom_domain TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Leads (Contacts from LP forms)
CREATE TABLE leads (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    landing_page_id UUID REFERENCES landing_pages(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    message TEXT,
    status TEXT DEFAULT 'new', -- 'new', 'contacted', 'converted', 'lost'
    metadata JSONB, -- User agent, referral, etc.
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Analytics Events
CREATE TABLE analytics_events (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    landing_page_id UUID REFERENCES landing_pages(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL, -- 'view', 'click_whatsapp', 'form_submit'
    device_type TEXT, -- 'mobile', 'desktop', 'tablet'
    referrer TEXT,
    ip_hash TEXT, -- To count unique visitors
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS Policies (Basic)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE landing_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE analytics_events ENABLE ROW LEVEL SECURITY;

-- Users can only read/edit their own profile
CREATE POLICY "Users can view own profile" ON users FOR SELECT USING (auth.uid()::text = clerk_id);
CREATE POLICY "Users can update own profile" ON users FOR UPDATE USING (auth.uid()::text = clerk_id);

-- LPs belong to users
CREATE POLICY "Users can view own LPs" ON landing_pages FOR SELECT USING (
    user_id IN (SELECT id FROM users WHERE clerk_id = auth.uid()::text)
);
CREATE POLICY "Users can insert own LPs" ON landing_pages FOR INSERT WITH CHECK (
    user_id IN (SELECT id FROM users WHERE clerk_id = auth.uid()::text)
);
CREATE POLICY "Users can update own LPs" ON landing_pages FOR UPDATE USING (
    user_id IN (SELECT id FROM users WHERE clerk_id = auth.uid()::text)
);

-- Leads belong to LPs which belong to users
CREATE POLICY "Users can view leads of their LPs" ON leads FOR SELECT USING (
    landing_page_id IN (
        SELECT id FROM landing_pages WHERE user_id IN (
            SELECT id FROM users WHERE clerk_id = auth.uid()::text
        )
    )
);

-- Public access policies for LP viewing and Lead submission
CREATE POLICY "Anyone can view published LPs" ON landing_pages FOR SELECT USING (status = 'published');
CREATE POLICY "Anyone can insert leads" ON leads FOR INSERT WITH CHECK (true);
CREATE POLICY "Anyone can insert analytics" ON analytics_events FOR INSERT WITH CHECK (true);
